# Generated by Django 4.2.1 on 2023-06-13 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_address_line_1_address_address_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address_line_2",
            new_name="address_line2",
        ),
    ]
